### PR TITLE
Enhancements regarding the support of non Unix-like operating systems

### PR DESCRIPTION
**Pull request by sk13**
This would support execution on operating systems which uses a path seperator character different from '/' (e.g Windows).

### CODE REVIEW

**Comment by WadeBarnes** [comment]
Updated the code to be inline with `main`.  Waiting to see the results from the checks and tests.

**Comment by WadeBarnes** [comment]
@sk13, Can you look into the formatting and test errors to see if they have anything to do with your changes.  Thanks

**Comment by dbluhm** [comment]
@sk13 are you available to look at these test failures? If not, I might be able to volunteer some time from someone on my team to fix this up and resolve conflicts.

**Comment by dbluhm** [comment]
See #2327

**Pull request closed without merging**
