### PR TITLE
match get-did-list to response "public" schema spec and fix misleadin…

### PR DESCRIPTION
**Pull request by sklump**
…g description text

https://github.com/hyperledger/aries-cloudagent-python/issues/676

Signed-off-by: sklump <srklump@hotmail.com>

### CODE REVIEW

**Comment by jcourt562** [comment]
So the scenario I am doing is that a user creates multiple private DIDs using POST /wallet/did/create.  The intention for this could be to create connections or use in create credential definitions with a different DID for various reasons (i.e avoiding correlation).  At some point they may need to write those DIDs to the ledger using POST /ledger/register-nym.  In order to show them which DIDs are on at the ledger (i.e. and so can't be written again) so that for example if they want to swap their current DID in use, I need to know which ones are written to ledger.  Since GET /wallet/did doesn't return an indication of which are written to ledger I am currently having to perform GET /ledger/did-verkey.  Is there a better way ? I assume GET /wallet/did even with filtering indicating public won't work as if it did it would make sense to return the "on ledger" status in the existing responses rather than just the indication for which did is currently being used by ACA-py ?

When you say they have been superseded, I don't see anything in the swagger ui indicating GET ledger/did-verkey is deprecated or superseded ?  If they are what is the replacement ?

Thanks

**Comment by sklump** [comment]
You are following the best practice as it stands.

We plan to revisit public/local DIDs after 0.5.4 because of the awkwardness you raise here. On-ledger or off-ledger ought to be in metadata and available via the wallet API. However, I suspect this will have a lot of tricky affected-bys and so it waits until we get the current release out.

**Comment by jcourt562** [comment]
Thanks for the feedback !

**Comment by sklump** [comment]
Please check your rocket chat for further discussion.

**Pull request merged**
