### PR TITLE
Aca-Py test scenario including a container restart (with aca-py version upgrade)

### PR DESCRIPTION
**Pull request by ianco**
Test for Issue #3269.

Script starts agents using docker-compose - alice agent is based on the Aca-Py 1.0.1 release image.  Alice connects with and then issues a credential to bob and then the test shuts down the alice agent, restarts based on the `acapy-test` image (based on the local aca-py codebase) and then asks for a proof.

This is working!  I'm going to release this PR as a simple test-with-restart and do a separate test with an askar-to-anoncreds wallet upgrade.

### CODE REVIEW

**Comment by jamshale** [comment]
I believe you can add assertions into the example.py script. Basically if it exits with exit code 1 it fails and if it exists with exit code 0 it passes. There's some caveats with this though. I had a test exiting with code 0 locally but it failed with github actions because the acapy-controller library never received an event it was expecting.

If the example raises an exception then it will fail.

**Review by jamshale — APPROVED** [review]
Looks good to me! 

Some of those docker attrs are pretty complicated and might be fragile to upgrading the docker package, but upgrading it won't be necessary for a testing project so that ok.

**Comment by ianco** [comment]
> Some of those docker attrs are pretty complicated and might be fragile to upgrading the docker package, but upgrading it won't be necessary for a testing project so that ok.

Yah I agree.  For some of the docker stuff it was a bit of trial and error so I'm not sure how fragile these tests are going to be :-S

**Review by dbluhm — APPROVED** [review]
I'm interested in potentially pulling some of that docker management complexity into an extra of the acapy_controller library in the future. That could be a convenient way to develop more of this style of test. As it stands, I think this is a great addition and I'm eager to get this kind of testing into the pipeline.

**Comment by ianco** [comment]
> I'm interested in potentially pulling some of that docker management complexity into an extra of the acapy_controller library in the future. That could be a convenient way to develop more of this style of test. 

Agree.  I've started a second test (to include an askar-to-anoncreds) upgrade.  For now I'll refactor the common stuff into a `util.py` (in acapy repo) but agree this should eventually be a feature of the `acapy_controller`.

**Pull request merged**
