### PR TITLE
Anoncreds post api object handling

### PR DESCRIPTION
**Pull request by jamshale**
The required values in the anoncreds POST object need to declare them as required explicitly to get the desired response.

```json
{
  "json": {
    "schema": {
      "issuerId": [
        "Missing data for required field."
      ]
    }
  }
}
```

### CODE REVIEW

**Comment by jamshale** [comment]
This ones pretty small but would be good to get in.

**Review by swcurran — APPROVED** [review]

**Review by ianco — APPROVED** [review]

**Comment by swcurran** [comment]
The restart test failed.  @jamshale @ianco -- are you looking at it?

**Comment by ianco** [comment]
> The restart test failed. @jamshale @ianco -- are you looking at it?

I'll take a look

**Comment by ianco** [comment]
I get this error running on my local:

```
alice-1           | 2024-12-20 18:13:15,476 acapy_agent.core.conductor ERROR DON'T shutdown on AnonCredsResolutionError No resolver available for identifier JmrNFeu93SVLXD511k26An:2:minimal-f9cd7740562fb7b3:1.0
alice-1           | 2024-12-20 18:13:15,476 acapy_agent.core.dispatcher ERROR Handler error: Dispatcher.handle_v1_message
alice-1           | Traceback (most recent call last):
alice-1           |   File "/usr/local/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
alice-1           |     result = coro.send(None)
alice-1           |              ^^^^^^^^^^^^^^^
alice-1           |   File "/usr/src/app/acapy_agent/core/dispatcher.py", line 258, in handle_v1_message
alice-1           |     await handler(context, responder)
alice-1           |   File "/usr/src/app/acapy_agent/protocols/present_proof/v2_0/handlers/pres_handler.py", line 53, in handle
alice-1           |     pres_ex_record = await pres_manager.receive_pres(
alice-1           |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
alice-1           |   File "/usr/src/app/acapy_agent/protocols/present_proof/v2_0/manager.py", line 354, in receive_pres
alice-1           |     receive_pres_return = await pres_format.handler(
alice-1           |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
alice-1           |   File "/usr/src/app/acapy_agent/protocols/present_proof/v2_0/formats/anoncreds/handler.py", line 332, in receive_pres
alice-1           |     await _check_proof_vs_proposal()
alice-1           |   File "/usr/src/app/acapy_agent/protocols/present_proof/v2_0/formats/anoncreds/handler.py", line 203, in _check_proof_vs_proposal
alice-1           |     schema = await registry.get_schema(self.profile, schema_id)
alice-1           |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
alice-1           |   File "/usr/src/app/acapy_agent/anoncreds/registry.py", line 80, in get_schema
alice-1           |     resolver = await self._resolver_for_identifier(schema_id)
alice-1           |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
alice-1           |   File "/usr/src/app/acapy_agent/anoncreds/registry.py", line 52, in _resolver_for_identifier
alice-1           |     raise AnonCredsResolutionError(
alice-1           | acapy_agent.anoncreds.base.AnonCredsResolutionError: No resolver available for identifier JmrNFeu93SVLXD511k26An:2:minimal-f9cd7740562fb7b3:1.0
```

**Comment by jamshale** [comment]
> I get this error running on my local:

Has something to do with the anoncreds issuance PR that got merged just before this... Not sure why yet.

**Comment by jamshale** [comment]
Ahh. I didn't think the holder hit this code. Not sure why it wasn't caught by the other tests.

I think I know how to fix it.

**Comment by jamshale** [comment]
Hmm. It's not what I thought originally. The askar issuer (alice) is sending an indy presentation request but getting back a presentation in anoncreds format from bob_anoncreds. It should be sending it in indy format. Not sure where it's happening though. This was tested in the anoncreds_issuance_and_revocation scenario as well.

**Pull request merged**
