### PR TITLE
Patch PR 3391 - 0.12.lts

### PR DESCRIPTION
**Pull request by jamshale**
We need someone from hyperledger to set the new HYPERLEDGER_GHCR_PAT token in the openwallet-foundation repo. See https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-with-a-personal-access-token-classic

> secrets.HYPERLEDGER_GHCR_PAT

### CODE REVIEW

**Comment by jamshale** [comment]
All the tests passed for this patch, so I think we can go ahead.

**Review by swcurran — APPROVED** [review]
LGTM

**Comment by jamshale** [comment]
The image succeeded 🚀 https://github.com/orgs/hyperledger/packages/container/package/aries-cloudagent-python

I'm not sure what to do about the pypi package though. I think we could try creating a 0.12.3 release if required. Because the image is the preferred way to deploy acapy, maybe we can get away with just having the patched image? 

Not really sure what happened with the package for previous patches...

**Comment by swcurran** [comment]
I can create a new release on the 0.12 branch — is that the next step?  That should publish the PyPi package, if the scripts work as expected, right?  Let me know and I’ll create the PR.

**Pull request merged**
